apiVersion: apps/v1
kind: Deployment
metadata:
  name: speeddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speed
      version: "2.0"
  template:
    metadata:
      labels:
        app: speed
        version: "2.0"
    spec:
      containers:
        - name: speedcontainer
          image: thummalalakshmanreddy/speed:2.0
          ports:
            - containerPort: 8080
              name: tomcatport
              protocol: TCP

